### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/GradeCraft#116]
Connect Cosign with Sorcery

**Comment by kevinchampion** [comment]
I don't imagine it will be, but if it's of help I can walk you through how the process logic in Cosign module in Drupal works (I rewrote chunks of it). By 'process logic' I mean how it matches the remote user (uniqname) as retrieved from apache Cosign to local Drupal users, and what it does for all the edge cases (remote user local user mismatch, remote user doesn't have local user, dealing with UM Friend accounts, user logout, invalid login, etc.).
