### ISSUE TITLE
Release grades method

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/GradeCraft#24]

**Comment by allspiritseve** [comment]
What is this?

**Comment by chcholman** [comment]
Assignment grades (one offs) need a state field that reflects whether they've been graded (which allows the teaching staff to do all their marking, review, compare, etc.) but not yet shown to students, and then the ability to release those grades as a batch.

**Comment by allspiritseve** [comment]
As we discussed, add a released/graded field to Grade and add a default scope so that whenever you are querying for grades, you always return released grades. To get unreleased grades, do something like this:

> Grade.where(:released => false)

Or even add a scope :unreleased that does the same where query.
