### ISSUE TITLE
Reading reaction scores from students feed into team points

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/GradeCraft#28]

**Comment by allspiritseve** [comment]
Team points = sum of reading scores for all students in the team? Or are there other ways teams get points? Do all reading reactions count, or just certain ones?

**Comment by chcholman** [comment]
Teams get points from the team challenges, which are just assignments for teams. One of those challenges is reading reactions. Each time a student makes it to the semis for reading reactions their team earns 500 points.

**Comment by allspiritseve** [comment]
Ok so team challenges (that are not reading reactions) should reference the team (belongs_to :team, has_many :assignments)

Then you can do something like this in the Team model:

def score
  challenge_score = assignments.grades.map(&:score).inject(&:+)
  reading_reaction_score = 500 \* users.grades.reading_reactions.map { |g| 1 if g.semifinalist? }.inject(&:+)
  challenge_score + reading_reaction_score
end

(Off topic: can you look at the ReadingReaction model? I suspect that most of what's in there really belongs to Grade (or a subclass of Grade).
