### ISSUE TITLE
Create subclasses for grades

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/GradeCraft#4]

**Comment by allspiritseve** [comment]
What subclasses are these?

**Comment by chcholman** [comment]
Attendance (twice a week, 5000 points each), reading reactions (once a week, three levels of points), and blogging (two levels of points possible, capped at 20000 points a month)

**Comment by allspiritseve** [comment]
This is done. Can you look at assignments#index and #new (for each subclass) and make sure things look ok? For reading reactions, did I do the point_total right? I wasn't sure if "Complete" was something that was supposed to go on grade.
