### ISSUE TITLE
Test Issue: Did you receive this?

### ISSUE THREAD

**Issue by allspiritseve** [UM-USElab/GradeCraft#69]

**Comment by tsuchii** [comment]
Yep

## 

Scott Tsuchiyama
269.274.3581
http://tsuch.net

**Comment by allspiritseve** [comment]
Thanks! That actually helped me narrow down the cause of Cait's lack of notifications. I'm going to create one more just to make sure the fix I did worked.

**Comment by kevinchampion** [comment]
I received this too.
